const fs=require('fs'),path=require('path'),{spawn}=require('child_process');
const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=path.resolve(process.argv[2]),video=process.argv.includes('--video');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-unsafe-swiftshader','--disable-web-security']});const page=await browser.newPage({viewport:{width:1440,height:1030},deviceScaleFactor:1}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('file://'+base+'/index.html');await page.waitForFunction(()=>!!window.film);await page.evaluate(()=>document.fonts.ready);const duration=await page.evaluate(()=>window.film.duration);
for(const t of [0,5,9.5,14,14.3,20,27]){await page.evaluate(t=>window.film.seek(t),t);await page.locator('#film').screenshot({path:path.join(base,`review-${t}.png`)});}
const checked=await page.evaluate(()=>{const d=window.film.data;if(d.imaginary_count!==1||d.modes[0].eligible||!d.modes[1].eligible)throw Error('Wrong mode eligibility');const a=window.film.seek(14.3),b=window.film.seek(3),c=window.film.seek(14.3);if(JSON.stringify(a)!==JSON.stringify(c))throw Error('Seek depends on order');return{atoms:d.atoms,modes:d.modes.map(m=>({index:m.index,frequency:m.frequency,overlap:m.overlap,selected:m.selected})),seekOrderIndependent:true};});
if(video){const fps=24,encoder=spawn(process.env.FFMPEG||'ffmpeg',['-y','-f','image2pipe','-vcodec','png','-framerate',String(fps),'-i','-','-an','-c:v','libx264','-threads','4','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',path.join(base,'rp-to-ts-mode.mp4')],{stdio:['pipe','ignore','pipe']});let log='';encoder.stderr.on('data',b=>log+=b);const done=new Promise((resolve,reject)=>{encoder.on('close',c=>c?reject(Error(log)):resolve());encoder.on('error',reject)});for(let i=0;i<duration*fps;i++){await page.evaluate(t=>window.film.seek(t),i/fps);const png=await page.locator('#film').screenshot();if(!encoder.stdin.write(png))await new Promise(r=>encoder.stdin.once('drain',r));if(i%(fps*4)===0)console.log('Rendered',i/fps,'/',duration,'seconds');}encoder.stdin.end();await done;}
fs.writeFileSync(path.join(base,'browser-validation.json'),JSON.stringify({status:errors.length?'failed':'passed',errors,video,viewport:[1440,900],...checked},null,2)+'\n');await browser.close();if(errors.length)throw Error(errors.join('\n'));
})().catch(e=>{console.error(e);process.exit(1)});
