const fs=require('fs'),path=require('path'),{spawn}=require('child_process');
const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=path.resolve(process.argv[2]),video=process.argv.includes('--video');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-unsafe-swiftshader','--disable-web-security']});
 const page=await browser.newPage({viewport:{width:1440,height:1030},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('file://'+base+'/index.html');await page.waitForFunction(()=>!!window.film);await page.evaluate(()=>document.fonts.ready);
 const duration=await page.evaluate(()=>window.film.duration);
 for(const t of [0,3,5,9,13,17.8,19.6,24]){await page.evaluate(t=>window.film.seek(t),t);await page.locator('#film').screenshot({path:path.join(base,`review-${t}.png`)});}
 const checked=await page.evaluate(()=>{const seen=new Set();let prior=0;for(let i=0;i<window.film.duration*24;i++){const s=window.film.seek(i/24);if(new Set(Object.values(s.mapping)).size!==s.assigned)throw Error('Noninjective displayed mapping');if(s.assigned<prior)throw Error('Growth shrank');prior=s.assigned;if(s.step>=0)seen.add(s.step);}if(seen.size!==135)throw Error('Skipped an atom addition');const end=window.film.seek(24);if(!end.verified||end.assigned!==135||end.missing!==0||end.extra!==0||end.fragments!==1)throw Error('Incorrect verification');return{frames:28*24,growth_steps:seen.size,final:end};});
 if(video){const fps=24;const encoder=spawn(process.env.FFMPEG||'ffmpeg',['-y','-f','image2pipe','-vcodec','png','-framerate',String(fps),'-i','-','-an','-c:v','libx264','-threads','4','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',path.join(base,'molecule-verification.mp4')],{stdio:['pipe','ignore','pipe']});let log='';encoder.stderr.on('data',b=>log+=b);const done=new Promise((resolve,reject)=>{encoder.on('close',c=>c?reject(Error(log)):resolve());encoder.on('error',reject);});for(let i=0;i<duration*fps;i++){await page.evaluate(t=>window.film.seek(t),i/fps);const png=await page.locator('#film').screenshot();if(!encoder.stdin.write(png))await new Promise(r=>encoder.stdin.once('drain',r));if(i%(fps*4)===0)console.log('Rendered',i/fps,'/',duration,'seconds');}encoder.stdin.end();await done;}
 fs.writeFileSync(path.join(base,'browser-validation.json'),JSON.stringify({status:errors.length?'failed':'passed',errors,video,viewport:[1440,900],frames_checked:checked.frames,recorded_growth_steps_shown:checked.growth_steps,all_atom_additions_shown:true},null,2)+'\n');await browser.close();if(errors.length)throw Error(errors.join('\n'));
})().catch(e=>{console.error(e);process.exit(1)});
